#!/bin/bash

sed -i 's/theta1/cjoints[0]/g' $1
sed -i 's/theta2/cjoints[1]/g' $1
sed -i 's/theta3/cjoints[2]/g' $1
sed -i 's/theta4/cjoints[3]/g' $1
sed -i 's/vl1/cvjoints[0]/g' $1
sed -i 's/vl2/cvjoints[1]/g' $1
sed -i 's/vl3/cvjoints[2]/g' $1
sed -i 's/vl4/cvjoints[3]/g' $1
sed -i 's/ac1/cajoints[0]/g' $1
sed -i 's/ac2/cajoints[1]/g' $1
sed -i 's/ac3/cajoints[2]/g' $1
sed -i 's/ac4/cajoints[3]/g' $1

sed -i 's/aX/hget(cacc,x)/g' $1
sed -i 's/aY/hget(cacc,y)/g' $1
sed -i 's/aZ/hget(cacc,z)/g' $1
sed -i 's/aY/hget(cacc,phi)/g' $1
sed -i 's/vX/hget(cvel,x)/g' $1
sed -i 's/vY/hget(cvel,y)/g' $1
sed -i 's/vZ/hget(cvel,z)/g' $1
sed -i 's/vY/hget(cvel,phi)/g' $1
sed -i 's/X/hget(cpose,x)/g' $1
sed -i 's/Y/hget(cpose,y)/g' $1
sed -i 's/Z/hget(cpose,z)/g' $1
sed -i 's/Y/hget(cpose,phi)/g' $1

sed -i 's/a1/ca[0]/g' $1
sed -i 's/a2/ca[1]/g' $1
sed -i 's/a3/ca[2]/g' $1
sed -i 's/a4/ca[3]/g' $1
sed -i 's/alpha1/calpha[0]/g' $1
sed -i 's/alpha2/calpha[1]/g' $1
sed -i 's/alpha3/calpha[2]/g' $1
sed -i 's/alpha4/calpha[3]/g' $1
sed -i 's/d1/cd[0]/g' $1
sed -i 's/d2/cd[1]/g' $1
sed -i 's/d3/cd[2]/g' $1
sed -i 's/d4/cd[3]/g' $1

sed -i 's/m1/cm[0]/g' $1
sed -i 's/m2/cm[1]/g' $1
sed -i 's/m3/cm[2]/g' $1
sed -i 's/m4/cm[3]/g' $1
sed -i 's/mm1/cmm[0]/g' $1
sed -i 's/mm2/cmm[1]/g' $1
sed -i 's/mm3/cmm[2]/g' $1
sed -i 's/mm4/cmm[3]/g' $1
sed -i 's/Ix1/ci[0][0]/g' $1
sed -i 's/Iy1/ci[0][1]/g' $1
sed -i 's/Iz1/ci[0][2]/g' $1
sed -i 's/Ix2/ci[1][0]/g' $1
sed -i 's/Iy2/ci[1][1]/g' $1
sed -i 's/Iz2/ci[1][2]/g' $1
sed -i 's/Ix3/ci[2][0]/g' $1
sed -i 's/Iy3/ci[2][1]/g' $1
sed -i 's/Iz3/ci[2][2]/g' $1
sed -i 's/Ix4/ci[3][0]/g' $1
sed -i 's/Iy4/ci[3][1]/g' $1
sed -i 's/Iz4/ci[3][2]/g' $1


